name: SonarQube Analysis

on:
  workflow_dispatch:
  push:
    branches:
      - main # Замініть на відповідну назву вашої основної гілки

jobs:
  build:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SonarQube Scan
        run: |
          docker run --rm \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -v "${PWD}:/usr/src" \
            sonarsource/sonar-scanner-cli
